"""
Schema annotations — persist and load column descriptions to/from a markdown file.

The file is human-editable. Format:

  # FINMAN Schema Annotations
  ## table_name
  | Column | Type | Description |
  |--------|------|-------------|
  | col    | text | My description |

On startup the scanner loads this file so the user is never asked the same
clarification question twice.
"""
from __future__ import annotations
import re
from pathlib import Path

ANNOTATIONS_FILE = Path("schema_annotations.md")


# ── Save ──────────────────────────────────────────────────────────────────────

def save_annotations(schema: dict[str, dict]) -> None:
    """Write all column descriptions to schema_annotations.md."""
    lines: list[str] = [
        "# FINMAN Schema Annotations\n",
        "_Auto-generated by FINMAN Agent. "
        "Edit descriptions freely — they are loaded on every startup "
        "so you won't be asked again._\n",
    ]

    for table, cols in sorted(schema.items()):
        lines.append(f"\n## {table}\n")
        lines.append("| Column | Type | Description |")
        lines.append("|--------|------|-------------|")
        for col, meta in cols.items():
            desc = (meta.get("description") or "").replace("|", "\\|")
            col_type = meta.get("type", "")
            lines.append(f"| {col} | {col_type} | {desc} |")

    ANNOTATIONS_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


# ── Load ──────────────────────────────────────────────────────────────────────

def load_annotations() -> dict[str, str]:
    """
    Parse schema_annotations.md and return a flat dict:
      { "table_name.column_name": "description", ... }

    Returns an empty dict if the file does not exist or cannot be parsed.
    """
    if not ANNOTATIONS_FILE.exists():
        return {}

    text = ANNOTATIONS_FILE.read_text(encoding="utf-8")
    annotations: dict[str, str] = {}
    current_table: str | None = None

    # Match "## table_name" section headers
    table_header = re.compile(r"^##\s+(\S+)", re.MULTILINE)
    # Match table rows:  | col | type | description |
    table_row = re.compile(r"^\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|\s*([^|]*?)\s*\|$")

    for line in text.splitlines():
        header_match = table_header.match(line)
        if header_match:
            current_table = header_match.group(1).strip()
            continue

        if current_table:
            row_match = table_row.match(line)
            if row_match:
                col = row_match.group(1).strip()
                desc = row_match.group(3).strip().replace("\\|", "|")
                # Skip the markdown header separator row (---|---|---)
                if col.startswith("-") or col.lower() == "column":
                    continue
                if desc:
                    annotations[f"{current_table}.{col}"] = desc

    return annotations
